// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgest.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getByCategory = `-- name: GetByCategory :one
SELECT id, user_id, category, limit_amount, period
FROM budgets
WHERE user_id = $1
  AND category = $2
`

type GetByCategoryParams struct {
	UserID   uuid.UUID
	Category string
}

func (q *Queries) GetByCategory(ctx context.Context, arg GetByCategoryParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getByCategory, arg.UserID, arg.Category)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.LimitAmount,
		&i.Period,
	)
	return i, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, user_id, category, limit_amount, period
FROM budgets
WHERE user_id = $1
ORDER BY category
`

func (q *Queries) ListBudgets(ctx context.Context, userID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, listBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.LimitAmount,
			&i.Period,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT DISTINCT category
FROM expenses
WHERE user_id = $1
`

func (q *Queries) ListExpenseCategories(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO budgets (user_id, category, limit_amount, period)
VALUES ($1, $2, $3, $4)
    ON CONFLICT (user_id, category)
DO UPDATE SET
    limit_amount = EXCLUDED.limit_amount,
           period       = EXCLUDED.period
`

type UpsertBudgetParams struct {
	UserID      uuid.UUID
	Category    string
	LimitAmount decimal.Decimal
	Period      string
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, upsertBudget,
		arg.UserID,
		arg.Category,
		arg.LimitAmount,
		arg.Period,
	)
	return err
}
