// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getBudgetLimit = `-- name: GetBudgetLimit :one
SELECT limit_amount
FROM budgets
WHERE category = $1
FOR UPDATE
`

func (q *Queries) GetBudgetLimit(ctx context.Context, category string) (decimal.Decimal, error) {
	row := q.db.QueryRowContext(ctx, getBudgetLimit, category)
	var limit_amount decimal.Decimal
	err := row.Scan(&limit_amount)
	return limit_amount, err
}

const getSumByCategory = `-- name: GetSumByCategory :one
SELECT COALESCE(SUM(amount), 0)::DECIMAL(14,2)
FROM expenses
WHERE user_id = $1
  AND category = $2
`

type GetSumByCategoryParams struct {
	UserID   uuid.UUID
	Category string
}

func (q *Queries) GetSumByCategory(ctx context.Context, arg GetSumByCategoryParams) (decimal.Decimal, error) {
	row := q.db.QueryRowContext(ctx, getSumByCategory, arg.UserID, arg.Category)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const insertExpense = `-- name: InsertExpense :one
INSERT INTO expenses (user_id, amount, category, description, date)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id
`

type InsertExpenseParams struct {
	UserID      uuid.UUID
	Amount      decimal.Decimal
	Category    string
	Description sql.NullString
	Date        time.Time
}

func (q *Queries) InsertExpense(ctx context.Context, arg InsertExpenseParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertExpense,
		arg.UserID,
		arg.Amount,
		arg.Category,
		arg.Description,
		arg.Date,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, user_id, amount, category, description, date
FROM expenses
WHERE user_id = $1
ORDER BY date DESC, id DESC
`

func (q *Queries) ListExpenses(ctx context.Context, userID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumByCategoryAndPeriod = `-- name: SumByCategoryAndPeriod :one
SELECT COALESCE(SUM(amount), 0)::DECIMAL(14,2)
FROM expenses
WHERE user_id = $1
  AND category = $2
  AND date BETWEEN $3 AND $4
`

type SumByCategoryAndPeriodParams struct {
	UserID   uuid.UUID
	Category string
	FromDate time.Time
	ToDate   time.Time
}

func (q *Queries) SumByCategoryAndPeriod(ctx context.Context, arg SumByCategoryAndPeriodParams) (decimal.Decimal, error) {
	row := q.db.QueryRowContext(ctx, sumByCategoryAndPeriod,
		arg.UserID,
		arg.Category,
		arg.FromDate,
		arg.ToDate,
	)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}
