// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Budget struct {
	ID          int32
	UserID      uuid.UUID
	Category    string
	LimitAmount decimal.Decimal
	Period      string
}

type Expense struct {
	ID          int32
	UserID      uuid.UUID
	Amount      decimal.Decimal
	Category    string
	Description sql.NullString
	Date        time.Time
}
