// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const reportSummary = `-- name: ReportSummary :many
SELECT
    category,
    COALESCE(SUM(amount), 0)::DECIMAL(14,2) AS total
FROM expenses
WHERE user_id = $1
  AND date BETWEEN $2 AND $3
ORDER BY category
`

type ReportSummaryParams struct {
	UserID   uuid.UUID
	FromDate time.Time
	ToDate   time.Time
}

type ReportSummaryRow struct {
	Category string
	Total    decimal.Decimal
}

func (q *Queries) ReportSummary(ctx context.Context, arg ReportSummaryParams) ([]ReportSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, reportSummary, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportSummaryRow
	for rows.Next() {
		var i ReportSummaryRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
